# Generated by Django 2.2.28 on 2023-07-14 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('severity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('weight', models.FloatField(default=1.0)),
                ('category', models.CharField(choices=[('HI', 'Historical'), ('FA', 'Facility')], default='FA', max_length=2)),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_risk_factors', to='app.RiskFactor')),
            ],
        ),
        migrations.CreateModel(
            name='RiskTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Response')),
                ('risk_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RiskFactor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='riskfactor',
            name='risk_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='app.RiskTopic'),
        ),
        migrations.AddField(
            model_name='riskfactor',
            name='trigger_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_risk_factors', to='app.Response'),
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('recommendations', models.ManyToManyField(to='app.Recommendation')),
                ('risk_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RiskTopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='risk_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='app.RiskFactor'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='risk_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RiskTopic'),
        ),
    ]
