# Generated by Django 2.2.28 on 2023-07-20 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='response_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
