# Generated by Django 2.2.28 on 2023-07-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userresponse_response_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='response_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
