# Generated by Django 2.2.28 on 2023-08-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_riskassessment_assesment_date_taken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together=set(),
        ),
    ]
