# Generated by Django 2.2.28 on 2023-08-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230810_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='risk_factor',
        ),
        migrations.AddField(
            model_name='riskfactor',
            name='responses',
            field=models.ManyToManyField(related_name='risk_factors', to='app.Response'),
        ),
    ]
