# Generated by Django 2.2.28 on 2023-09-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230828_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskfactor',
            name='trigger_response',
        ),
        migrations.AddField(
            model_name='riskfactor',
            name='trigger_response',
            field=models.ManyToManyField(blank=True, null=True, related_name='trigger_risk_factors', to='app.Response'),
        ),
    ]
