# Generated by Django 2.2.28 on 2023-10-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_aggregatereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfactor',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
