# Generated by Django 2.2.28 on 2023-10-25 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_riskfactor_is_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='expected_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Response'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('SB', 'Score Based'), ('RB', 'Response Based')], default='SB', max_length=2),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='risk_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.RiskFactor'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='max_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='min_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
