# Generated by Django 2.2.28 on 2023-10-30 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20231025_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='aggregate_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_assessments', to='app.AggregateReport'),
        ),
    ]
